# Generated by Django 4.2.26 on 2026-02-05 01:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the writing context (e.g., 'Professional Email')", max_length=100, unique=True)),
                ('description', models.TextField(help_text='Detailed description of when this context should be used')),
                ('guidelines', models.TextField(help_text='Specific guidelines for the LLM when rewriting in this context')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this context is available for users to select')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rewrite Context',
                'verbose_name_plural': 'Rewrite Contexts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ToneOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the tone (e.g., 'Polite', 'Professional')", max_length=50, unique=True)),
                ('description', models.TextField(help_text='Description of what this tone conveys')),
                ('prompt_modifier', models.TextField(help_text='Instructions added to the LLM prompt to achieve this tone')),
                ('intensity_level', models.PositiveSmallIntegerField(default=5, help_text='Intensity level from 1 (subtle) to 10 (strong)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this tone is available for users to select')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tone Option',
                'verbose_name_plural': 'Tone Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RewriteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField(help_text='The original text submitted by the user for rewriting', validators=[django.core.validators.MinLengthValidator(10)])),
                ('audience', models.CharField(blank=True, default='', help_text="Optional: intended audience (e.g., 'professor', 'manager')", max_length=100)),
                ('purpose', models.CharField(blank=True, default='', help_text="Optional: purpose of the text (e.g., 'request extension', 'follow up')", max_length=200)),
                ('session_token', models.CharField(help_text='Unique token to identify this session (for URL sharing)', max_length=64, unique=True)),
                ('is_completed', models.BooleanField(default=False, help_text='Whether rewrites have been successfully generated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.ForeignKey(help_text='The writing context selected for this rewrite', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='rewrites.rewritecontext')),
                ('tone', models.ForeignKey(help_text='The tone selected for this rewrite', on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='rewrites.toneoption')),
            ],
            options={
                'verbose_name': 'Rewrite Session',
                'verbose_name_plural': 'Rewrite Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RewriteResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewritten_text', models.TextField(help_text='The generated rewritten version of the original text')),
                ('version_label', models.CharField(help_text="Label for this version (e.g., 'A', 'B', 'C')", max_length=20)),
                ('change_summary', models.TextField(blank=True, default='', help_text='Optional summary of what was changed in this rewrite')),
                ('quality_score', models.CharField(choices=[('high', 'High Quality'), ('medium', 'Medium Quality'), ('low', 'Low Quality')], default='medium', help_text='Estimated quality of this rewrite', max_length=10)),
                ('word_count_original', models.PositiveIntegerField(default=0, help_text='Word count of the original text')),
                ('word_count_rewritten', models.PositiveIntegerField(default=0, help_text='Word count of this rewritten version')),
                ('is_selected', models.BooleanField(default=False, help_text='Whether the user selected/copied this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(help_text='The session this rewrite belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='rewrites.rewritesession')),
            ],
            options={
                'verbose_name': 'Rewrite Result',
                'verbose_name_plural': 'Rewrite Results',
                'ordering': ['session', 'version_label'],
            },
        ),
        migrations.AddConstraint(
            model_name='rewritesession',
            constraint=models.UniqueConstraint(fields=('original_text', 'context', 'tone'), name='unique_text_context_tone_combination'),
        ),
        migrations.AddConstraint(
            model_name='rewriteresult',
            constraint=models.UniqueConstraint(fields=('session', 'version_label'), name='unique_session_version_label'),
        ),
    ]
