# Generated by Django 6.0.2 on 2026-03-02 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewrites', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritesession',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user who created this session (null for legacy/anonymous)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
