# Generated by Django 5.2.6 on 2026-04-21 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewrites', '0003_seed_default_context_tone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AICallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('llm_rewrite', 'LLM Rewrite (API)'), ('local_rewrite', 'Local Rewrite (HF)'), ('semantic_search', 'Semantic Search')], help_text='Which AI feature was invoked', max_length=32)),
                ('model_name', models.CharField(blank=True, default='', help_text='Underlying model (e.g., gpt-4.1-mini, Qwen2.5-0.5B, MiniLM)', max_length=64)),
                ('latency_ms', models.PositiveIntegerField(default=0, help_text='End-to-end latency in milliseconds')),
                ('input_chars', models.PositiveIntegerField(default=0, help_text='Character count of the input text/query')),
                ('prompt_tokens', models.PositiveIntegerField(default=0, help_text='Approximate prompt/input tokens')),
                ('completion_tokens', models.PositiveIntegerField(default=0, help_text='Approximate completion/output tokens')),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('timeout', 'Timeout')], default='success', help_text='Outcome of the call', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, help_text='Related session (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to='rewrites.rewritesession')),
                ('user', models.ForeignKey(blank=True, help_text='User who triggered the call (null for anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_call_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Call Log',
                'verbose_name_plural': 'AI Call Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', 'created_at'], name='rewrites_ai_feature_ff90aa_idx'), models.Index(fields=['user', 'created_at'], name='rewrites_ai_user_id_a02e12_idx')],
            },
        ),
    ]
